### ISSUE TITLE
simplify simple-network.md

### ISSUE THREAD

**Issue by flokli** [astro/microvm.nix#116]
Currently, `simple-network.md` describes the network setup for MicroVMs using a TAP interface, which is then attached to a bridge, and then lists some systemd-network config necessary on the host to configure the network for internet access.

It however can become even simpler, *by only creating the TAP interface, and letting the rule systemd-networkd ships with take care of providing client internet access out of the box, without any additional config necessary on the host* (other than systemd-networkd):

https://github.com/systemd/systemd/pull/15447 added a [80-vm-vt.network](https://github.com/systemd/systemd/pull/15447/files#diff-7f84efcbf57c0c78206ebcb424ba8daecb7f6b52422b79035e2f66217bc18793) file which automatically spins up a DHCP server and configures NAT for TAP interfaces starting with `vt-`. This has been in systemd since more than 3 years, so we can assume it to be present.

My proposal would be to extend/update the microvm.nix tooling to create TAP interfaces with that prefix, and then simplify these docs. We could still document how to manually explicitly configure networking, but it should probably also be on the TAP interface, for better isolation of individual VMs from each other.

**Comment by Mic92** [comment]
@astro I can work on this, if you give me green light.

**Comment by astro** [comment]
Good idea, go ahead

**Comment by Mic92** [comment]
I played around with networkd's tap network unit but it wasn't working well.

1. Only ipv4 is supported:
  * It uses the `Address=0.0.0.0/24` to assign an ipv4 subnet. There is also `Address=::/64` for ipv6 however the dhcpv6 or router advertisment won't pick up subnets assigned like that.
2. Multiple subnets. Somehow I would after a while always end up with multiple subnets after a while on the interface instead of just one. This also sometimes broke the networking.

**Comment by pwaller** [comment]
FYI, I had difficulty getting the networking working, following the docs.

The root cause was a difference between simple-network.md and interfaces.md:

https://github.com/astro/microvm.nix/blob/67bf176ff48141292a66d8bce541463ee49d0fb5/doc/src/interfaces.md#L11

https://github.com/astro/microvm.nix/blob/67bf176ff48141292a66d8bce541463ee49d0fb5/doc/src/simple-network.md#L53

The id in the former does not match the expression in the latter, so the networkctl does not bind the tap interface to the bridge and therefore ends up in the 'no-carrier' state. Took me a while to figure out what was going on.

Scanning through the docs, it wasn't so easy to put together a working configuration quickly.

**Comment by astro** [comment]
@pwaller Thank you for reporting this inconsistency. Mended in ffa1fba

**Comment by astro** [comment]
I would like to provide that *simple-network* as a `nixosModule` someday.

**Comment by alexandru0-dev** [comment]
> Scanning through the docs, it wasn't so easy to put together a working configuration quickly.

i'm still trying to setup the vm's networking, tried almost everything with no success.
I have a `eno1` interface on the host with a static ip, ideally i want to have static ips for each microvm.
Any help? @astro

**Comment by jpds** [comment]
@alexandru0-dev The easiest way to accomplish this is to setup a bridge on the host with:

```
  systemd.network.enable = true;

  systemd.network.networks."10-lan" = {
    matchConfig.Name = ["eno1" "vm-*"];
    networkConfig = {
      Bridge = "br0";
    };
  };

  systemd.network.netdevs."br0" = {
    netdevConfig = {
      Name = "br0";
      Kind = "bridge";
    };
  };

  systemd.network.networks."10-lan-bridge" = {
    matchConfig.Name = "br0";
    networkConfig = {
      DHCP = "yes";
      IPv6AcceptRA = true;
    };
    linkConfig.RequiredForOnline = "routable";
  };
```

Adjust your bridge's `networkConfig` as required.

And on the microVM, set:

```
  systemd.network.enable = true;

  systemd.network.networks."20-lan" = {
    matchConfig.Type = "ether";
    networkConfig = {
      Address = ["192.168.1.2/24" "2001:db8::a/64"];
      Gateway = "192.168.1.1";
      DNS = ["192.168.1.1"];
      IPv6AcceptRA = true;
      DHCP = "no";
    };
  };
```

**Comment by alexandru0-dev** [comment]
@jpds thx, I got it working using the original example tho it's dchp so no static ip and even if I have an IP on the same subnet of my lan, they are not reachable from the lan.

Does your example also solve the second "issue"?
I will try it later
