### ISSUE TITLE
Support specifying vsock connections

### ISSUE THREAD

**Issue by Sohalt** [astro/microvm.nix#131]
It would be nice to be able to specify vsock connections for VMs, e.g. have cloud-hypervisor launch with the `--vsock /some/path` option.

**Comment by astro** [comment]
Good idea!

Do you think configuring just the socket path will be enough? What is your primary use-case? I was thinking about running [waypipe](https://gitlab.freedesktop.org/mstoeckl/waypipe/) through vsocks.

**Comment by Sohalt** [comment]
I wanted to have a way for a custom service to communicate between vm and host without using up ports on the host. For that specifying the path should be enough.

**Comment by astro** [comment]
What about the CID?

**Comment by astro** [comment]
Depending on the VMM, VSOCK are terminated differently:

* qemu, kvmtool, and crosvm support host AF_VSOCK which feels first-class. I added support for these three. If you want to translate into other socket domains use socat.
* cloud-hypervisor translates VSOCK connections to Unix Domain sockets, with the port interpolated into their paths.
* firecracker translates VSOCK connections to Unix Domain sockets but exposes a proxy protocol to the host so that the port can be passed.

**Comment by Ramblurr** [comment]
@Sohalt Astro implemented qemu vsock support back in 2023, and I've just now prepared an implementation PR for cloud-hypervisor  that you may want to play with: https://github.com/astro/microvm.nix/pull/379
