### ISSUE TITLE
Pass additional NixOS modules to VM

### ISSUE THREAD

**Issue by pizzapim** [astro/microvm.nix#197]
I use custom NixOS modules to make additional NixOS options available to my servers, and I would like to do the same for VMs. However, I could not find a way to do this. I am using the fully declarative MicroVM setup.

An option like the following would be awesome:
```nix
{ microvm, ... }: {
  imports = [ microvm.host ];
  microvm.vms = {
    my-microvm = {

      extraModules = [ ];

      config = {
        # [...]
      };
    };
  };
}
```

**Comment by astro** [comment]
NixOS modules are equivalent to NixOS configurations. Just add an `imports = [ ... ]` configuration to your NixOS.

**Comment by n1xn00b** [comment]
This might be a general problem with my understanding of nix but I think I have a similar issue: I'm trying to use [arion](https://github.com/hercules-ci/arion) inside a microvm which I added to my flake.nix as follows:
```
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.05";

    microvm.url = "github:microvm-nix/microvm.nix";
    microvm.inputs.nixpkgs.follows = "nixpkgs";

    arion.url = "github:hercules-ci/arion";
  };
  outputs = inputs@{ self, nixpkgs, microvm, arion, ... }: {
    nixosConfigurations.hostname = nixpkgs.lib.nixosSystem {
      specialArgs = { inherit inputs; };
      system = "x86_64-linux";
      modules = [
        ./configuration.nix
        microvm.nixosModules.host
        arion.nixosModules.arion

        {
          microvm.vms.docker.config = {
            imports = [ arion.nixosModules.arion ];
            virtualisation.arion = {
              backend = "docker";
              projects.test = {
                settings = {
                  services.postgres = {
                    service.image = "postgres:10";
                    service.volumes = [ "${toString ./.}/postgres-data:/var/lib/postgresql/data" ];
                    service.environment.POSTGRES_PASSWORD = "mydefaultpass";
                  };
                };
              };
            };
          };
        }
      ];
    };
  };
}

```

This works using your suggested solution (if I understood it correctly). However, when I move this out of my flake.nix (later I want it to be somewhere in my git repo imported from configuration.nix) and instead use something like 
```
modules = [
  ./configuration.nix
  microvm.nixosModules.host
  arion.nixosModules.arion
  ./docker-test.nix
];
```
 where docker-test.nix contains
```
{ arion, ... } :
{
  microvm.vms.docker.config = {
    imports = [ arion.nixosModules.arion ];
    virtualisation.arion = {
      backend = "docker";
      projects.jump-dashboard2 = {
        settings = {
          services.postgres = {
            service.image = "postgres:10";
            service.volumes = [ "${toString ./.}/postgres-data:/var/lib/postgresql/data" ];
            service.environment.POSTGRES_PASSWORD = "mydefaultpass";
          };
        };
      };
    };
  };
}
```
I get `error: attribute 'arion' missing` for the line where I try to import arion. The rest of the docker vm is in another file and hopefully not relevant since it works without the part shown above. I have tried various things but I don't understand how to import the module in this case. If your solution is still correct could you please specify how to apply it here?
