### ISSUE TITLE
Gain terminal access to a microvm controlled by systemd

### ISSUE THREAD

**Issue by RooSoft** [astro/microvm.nix#224]
Firstly, THANK YOU for that awesome project... I am considering migrating everything to microVMs once I get a solid grasp of how it all works.

Is there any way to gain terminal access to a running microvm controlled by systemd?

Not a sockets expert, but I have noticed that `/var/lib/microvms/myVM/control.socket` file that's available once the `myVM` microVM is in function... can it be used to get into the terminal?

Been searching `control.socket` in this project and I can't find any info about this...

**Comment by RooSoft** [comment]
Also, is there a forum or chat room where microVM enthousiasts hang out?

**Comment by astro** [comment]
Hi! Thank you for your kind words.
> Is there any way to gain terminal access to a running microvm controlled by systemd?

Not as is but there are a few possibilities:
- I just setup SSH.
- https://github.com/Mic92/vmsh is a very interesting project but it needs to be updated to catch up with the latest Linux kernel versions.
- We've had serial console setup for that. Search this project's git history for `microvm-console`. I dropped it because it was too cumbersome to keep across hypervisors but I am not fundamentally opposed to that feature.

> Not a sockets expert, but I have noticed that /var/lib/microvms/myVM/control.socket file that's available once the myVM microVM is in function... can it be used to get into the terminal?

No, the socket controls the Hypervisor. We use it for clean shutdown.

> Also, is there a forum or chat room where microVM enthousiasts hang out?

There's a Matrix room: https://matrix.to/#/#microvm.nix:envs.net

**Comment by srd424** [comment]
Excuse random closed-issue commenting, but .. modern systemd seems to support ssh listening over VSOCK sockets: https://www.freedesktop.org/software/systemd/man/latest/systemd-ssh-proxy.html - feels like it might be an elegant solution? I'd try to prepare a patch but I don't think my nix skills are anywhere near good enough :(
