### ISSUE TITLE
No Internet by Systemd-resolve.

### ISSUE THREAD

**Issue by GTrunSec** [astro/microvm.nix#25]
Could you confirm whether the tap in the example of the microvm.nix has internet access?
I can sure this problem is caused by DNS of the systemd-resolve.

How do we solve it by systemd-resolve.service?

**Comment by GTrunSec** [comment]
This issue was due to the namespace of my host

**Comment by GTrunSec** [comment]
The attached hosts still have no network.

**Comment by astro** [comment]
Please describe your networking setup in more detail. Do you bridge to a DHCP with public IP addresses, or did you setup NAT?

I am fine with giving usable defaults as long as they can be overriden for custom deployments.

**Comment by astro** [comment]
The example does not provide external network access. The `virbr0` bridge is only local inside the example VM, connecting the MicroVMs.

An option that always works would be using qemu's `user` interfaces.

What's the rationale behind having that in the example? An example shouldn't include too much so that lines of code are fewer in my opinion.

**Comment by GTrunSec** [comment]
This question is about virtual machine networking-related issues, it shouldn't open an issue. Thanks for you reply
