### ISSUE TITLE
Include in nix-community?

### ISSUE THREAD

**Issue by Pleune** [astro/microvm.nix#290]
I just stumbled across this, but it is genuinely amazing and works really well. To a point where I really want some indication that it will stick around for a while! It genuinely one of the simplest ways to build microvm infrastructure that I have seen so far.

In your presentation, you mention a possibility of financial support from Numtide. Would this include moving this project into nix-community?

**Comment by astro** [comment]
Hi!

I am very aware that a number of people use this and depend on it. That is precisely the reason why I don't want to invite other maintainers who might have other motivations over stability. I would be open to additional help if they can keep the stability promise.

Apart from a few Github sponsors, there is no financial support from companies unfortunately. They are available for commercial support because that frees me from caring about business matters myself. They're free to do whatever you task them as this project is MIT-licensed.

Of course I'll be very happy about incoming PRs, and I try to review them timely.

Ultimately, I believe that the functionality of microvm.nix and nixos-generators should be moved into nixpkgs just like nixos-containers already lives in there.
