### ISSUE TITLE
cloud-hypervisor tries to set up tap interfaces itself

### ISSUE THREAD

**Issue by MarcelCoding** [astro/microvm.nix#305]
```
Dez 06 11:58:41 svc-hv01 microvm@svc-cloud01[4150351]: cloud-hypervisor: 18.759205ms: <vmm> WARN:net_util/src/open_tap.rs:105 -- Tap s-svc-cloud01 already exists. IP configuration will not be
overwritten.
```

Config: https://github.com/dd-ix/nix-config/blob/6bb0d179bdc2f94860f91418c3fe6d71daa6e3a6/modules/dd-ix-microvm.nix#L42-L46

**Comment by astro** [comment]
> Tap s-svc-cloud01 already exists. IP configuration will not be
overwritten.

That message means it doesn't do anything to the tap interface (which is does not have permission for as non-root user). Is it failing for you?

**Comment by MarcelCoding** [comment]
No, the vm is booting just fine. It's just a normal waning in the journal logs before the kernel begins logging.

**Comment by astro** [comment]
The warning is currently not quelchable in cloud-hypervisor. Maybe this is an easy opportunity to get a first commit upstream.

**Comment by pwaller** [comment]
I suspect I'm seeing failures related to this in time. In conjunction with this message appearing, the microvms are failing to come up. A system built at 8am UTC on Dec 7th worked, one built 8am UTC on Dec 8th failed. I haven't time to root cause or provide other information immediately but wanted to share in case others have encountered this.

Rolling everything back worked, but was quite slow, with services taking a long time to restart. Journalctl is also extremely slow, typically taking 30 seconds before it even starts showing anything.

**Comment by astro** [comment]
@pwaller Please share the error message from your journal. Perhaps open a new issue. I doubt that this ticket is the culprit in your case.

**Comment by pwaller** [comment]
> @pwaller Please share the error message from your journal. Perhaps open a new issue. I doubt that this ticket is the culprit in your case.

It has proven difficult to get my hands on obvious indicators of what changed or what broke! I've tried to describe what I'm seeing on https://github.com/astro/microvm.nix/issues/312, I hope that is of use.
